build-linux-container-job:
  services:
    - name: docker:dind
      alias: docker
      command: ["--tls=false", "--insecure-registry=http://192.168.1.17:5050"]

  stage: build
  before_script:
    - echo $CI_REGISTRY
  script:
    - cd DockerFiles/
    #- echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t http://192.168.1.17:5050/destroypluto/practiceproject:linux -f linux.Dockerfile .
    - docker push http://192.168.1.17:5050/destroypluto/practiceproject:linux

build-linux-job:
  image: $CI_REGISTRY/destroypluto/practiceproject:linux
  stage: build
  needs: ["build-linux-container-job"]
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - cmake --fresh .
    - make
  artifacts:
    untracked: false
    when: on_success
    expire_in: 30 days
    paths:
      - "bin/*"

test-job1:
  stage: test
  script:
    - echo "This job tests something!"

deploy-prod:
  stage: deploy
  script:
    -  echo "This job deploys something from the $CI_COMMIT_BRANCH branch"
  environment: production
