#build-linux-container-job:
#  services:
#    - name: docker:24.0.6-dind
#      alias: dockerhost
#      command: ["--tls=false"]
#  variables:
#    DOCKER_HOST: tcp://dockerhost:2375
#    DOCKER_DRIVER: overlay2
#    DOCKER_TLS_CERTDIR: ""
#  stage: build
#  before_script:
#    - docker info
#  script:
#    - cd DockerFiles/
#    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
#    - docker build -t ${CI_REGISTRY}/destroypluto/practiceproject:linux -f linux.Dockerfile .
#    - docker push ${CI_REGISTRY}/destroypluto/practiceproject:linux

build-linux-job:
#  image: $CI_REGISTRY/destroypluto/practiceproject:linux
  image: ubuntu:latest
  stage: build
  before_script:
    - apt update
    - apt install -y cmake
    - apt install -y clang-16
    - apt install -y libwayland-dev 
    - apt install -y libxkbcommon-dev
    - apt install -y xorg-dev
    - export CXX=clang++
    - export CC=clang
#  needs: ["build-linux-container-job"]
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - cmake --fresh .
    - make
  artifacts:
    untracked: false
    when: on_success
    expire_in: 30 days
    paths:
      - "bin/*"

test-job1:
  stage: test
  script:
    - echo "This job tests something!"

deploy-prod:
  stage: deploy
  script:
    -  echo "This job deploys something from the $CI_COMMIT_BRANCH branch"
  environment: production
